#!/usr/bin/env node
// Regenerates packages/ui/src/Header/logo.ts.
//
// Renders bold monospace type onto a canvas in headless Chromium, then
// downsamples the glyph bitmap to a coarse character grid — filled cells
// become "#" — matching how docs/prototype/prototype.dc.html's LOGO_LINES
// was produced for "PLANIT POKER" (see its comment for the technique).
//
// Usage: node scripts/generate-logo.mjs ["VBS"] [--rows=16] [--print]

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { chromium } from "@playwright/test";

const args = process.argv.slice(2);
const positional = args.filter((a) => !a.startsWith("--"));
const flags = Object.fromEntries(
  args.filter((a) => a.startsWith("--")).map((a) => a.slice(2).split("=")),
);

const TEXT = positional[0] ?? "VBS";
// 16 rows (the prototype's own height) reproduces its "PLANIT POKER" texture
// almost exactly for a 12-character string, but for the 3 characters of
// "VBS" it renders smooth and legible rather than coarse. 10 rows keeps the
// same chunky, dot-matrix feel at this shorter length — tuned by eye against
// docs/prototype/prototype.dc.html's LOGO_LINES, not derived mathematically.
const ROWS = Number(flags.rows ?? 10);
const FONT_SIZE_PX = Number(flags.fontSize ?? 220);
const FONT_FAMILY = "'Courier New', Courier, monospace";
// Terminal character cells are taller than wide; this is Courier New's
// width:height ratio, used to keep the printed grid's proportions matching
// the source glyphs rather than stretching or squashing them.
const CHAR_ASPECT = 0.6;
// Matches --vbs-logo-line-height in tokens.css.
const LINE_HEIGHT_FACTOR = 1.05;
// Fraction of "ink" pixels a cell needs to print as "#".
const FILL_THRESHOLD = Number(flags.threshold ?? 0.3);

const OUTPUT_PATH = fileURLToPath(
  new URL("../packages/ui/src/Header/logo.ts", import.meta.url),
);

function rasterize({
  text,
  fontSizePx,
  fontFamily,
  charAspect,
  lineHeightFactor,
  rows,
  threshold,
}) {
  const measure = document.createElement("canvas").getContext("2d");
  measure.font = `bold ${fontSizePx}px ${fontFamily}`;
  const metrics = measure.measureText(text);
  const width = Math.max(1, Math.ceil(metrics.width));
  const ascent = Math.ceil(metrics.actualBoundingBoxAscent);
  const descent = Math.ceil(metrics.actualBoundingBoxDescent);
  const height = Math.max(1, ascent + descent);

  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext("2d");
  ctx.font = `bold ${fontSizePx}px ${fontFamily}`;
  ctx.fillStyle = "#000000";
  ctx.textBaseline = "alphabetic";
  ctx.fillText(text, 0, ascent);

  const { data } = ctx.getImageData(0, 0, width, height);
  const alphaAt = (x, y) => data[(y * width + x) * 4 + 3];

  const cols = Math.max(
    1,
    Math.round(rows * (1 / charAspect) * lineHeightFactor * (width / height)),
  );

  const lines = [];
  for (let r = 0; r < rows; r++) {
    const y0 = Math.floor((r / rows) * height);
    const y1 = Math.max(y0 + 1, Math.floor(((r + 1) / rows) * height));
    let line = "";
    for (let c = 0; c < cols; c++) {
      const x0 = Math.floor((c / cols) * width);
      const x1 = Math.max(x0 + 1, Math.floor(((c + 1) / cols) * width));
      let ink = 0;
      let total = 0;
      for (let y = y0; y < y1; y++) {
        for (let x = x0; x < x1; x++) {
          total++;
          if (alphaAt(x, y) > 128) ink++;
        }
      }
      line += ink / total > threshold ? "#" : " ";
    }
    lines.push(line.replace(/\s+$/, ""));
  }
  return lines;
}

const browser = await chromium.launch();
try {
  const page = await browser.newPage();
  const lines = await page.evaluate(rasterize, {
    text: TEXT,
    fontSizePx: FONT_SIZE_PX,
    fontFamily: FONT_FAMILY,
    charAspect: CHAR_ASPECT,
    lineHeightFactor: LINE_HEIGHT_FACTOR,
    rows: ROWS,
    threshold: FILL_THRESHOLD,
  });

  if (flags.print !== undefined) {
    console.log(lines.join("\n"));
  }

  const body = lines.map((line) => `  ${JSON.stringify(line)},`).join("\n");
  const source = `// Generated by scripts/generate-logo.mjs — do not hand-edit.
// Rerun: node scripts/generate-logo.mjs "${TEXT}"

export const LOGO_LINES = [
${body}
] as const;

export const LOGO_TEXT = LOGO_LINES.join("\\n");
`;

  await writeFile(OUTPUT_PATH, source, "utf-8");
  console.log(`Wrote ${lines.length} lines to ${OUTPUT_PATH}`);
} finally {
  await browser.close();
}
